
create table alert_rule_vehicles (
rule_id bigint not null,
vehicle_id varchar(255)
);
create table alert_rules (
cooldown_minutes integer,
is_enabled boolean,
priority integer,
created_at timestamp(6) with time zone,
organization_id bigint,
rule_id bigint generated by default as identity,
updated_at timestamp(6) with time zone,
created_by varchar(100),
rule_key varchar(100) not null unique,
rule_name varchar(200) not null,
actions JSONB,
conditions JSONB,
notification_channels JSONB,
parameters JSONB not null,
rule_type enum ('BUSINESS_RULE','CUSTOM','DEVICE_STATUS','GEOFENCE','SAFETY','SPEED','TIME','VEHICLE_STATUS') not null,
primary key (rule_id)
);
create table deliveries (
attemptCount integer not null,
maxAttempts integer not null,
createdAt timestamp(6) with time zone not null,
deliveredAt timestamp(6) with time zone,
device_id bigint,
id bigint generated by default as identity,
nextRetryAt timestamp(6) with time zone,
sentAt timestamp(6) with time zone,
updatedAt timestamp(6) with time zone not null,
deliveryId varchar(255) not null unique,
lastError TEXT,
message TEXT,
notification_id varchar(255),
recipient varchar(255) not null,
templateId varchar(255) not null,
templateVariables TEXT,
title varchar(255),
channel enum ('EMAIL','IN_APP','MOBILE_PUSH','SLACK','SMS','TEAMS','WEBSOCKET') not null,
lastErrorType enum ('PERMANENT','TRANSIENT'),
status enum ('DELIVERED','EXHAUSTED','FAILED','PENDING','SENDING','SENT','SKIPPED') not null,
primary key (id)
);
create table delivery_events (
id bigint generated by default as identity,
occurredAt timestamp(6) with time zone not null,
deliveryId varchar(255) not null,
metadata TEXT,
eventType enum ('CLICKED','CREATED','DELIVERED','EXHAUSTED','FAILED','OPENED','RETRY_SCHEDULED','SENT') not null,
primary key (id)
);
create table device_commands (
max_retries integer,
retry_count integer,
command_id bigint generated by default as identity,
created_at timestamp(6) with time zone,
responded_at timestamp(6) with time zone,
sent_at timestamp(6) with time zone,
updated_at timestamp(6) with time zone,
tracker_id varchar(50) not null,
initiated_by varchar(100),
command_data TEXT not null,
error_message TEXT,
response_data TEXT,
command_type enum ('CHANGE_PASSWORD','ENGINE_START','ENGINE_STOP','FACTORY_RESET','FUEL_CUT','FUEL_RESTORE','HISTORY_REQUEST','LOCATION_REQUEST','READ_STATUS','REBOOT_DEVICE','SET_ADMIN_NUMBER','SET_ALARM_MODE','SET_APN','SET_CENTER_NUMBER','SET_GEOFENCE','SET_HEARTBEAT_INTERVAL','SET_IP_PORT','SET_OVERSPEED_LIMIT','SET_WORKING_MODE','UPDATE_FIRMWARE') not null,
status enum ('CANCELLED','DELIVERED','FAILED','PENDING','SENT','TIMEOUT'),
primary key (command_id)
);
create table devices (
isValid boolean not null,
createdAt timestamp(6) with time zone not null,
id bigint generated by default as identity,
updatedAt timestamp(6) with time zone not null,
deviceId varchar(255) not null unique,
pushToken varchar(255),
tenantId varchar(255),
userId varchar(255) not null,
platform enum ('ANDROID','IOS','WEB') not null,
primary key (id)
);
create table geofence_points (
latitude float(53) not null,
longitude float(53) not null,
point_order integer not null,
created_at timestamp(6) with time zone,
geofence_id bigint not null,
point_id bigint generated by default as identity,
primary key (point_id)
);
create table geofence_vehicles (
geofence_id bigint not null,
vehicle_id varchar(50)
);
create table geofences (
center_latitude float(53),
center_longitude float(53),
is_active boolean,
radius_meters integer,
created_at timestamp(6) with time zone,
geofence_id bigint generated by default as identity,
organization_id bigint,
updated_at timestamp(6) with time zone,
created_by varchar(100),
name varchar(100) not null,
description varchar(500),
shape_type enum ('CIRCLE','POLYGON'),
primary key (geofence_id)
);
create table identities (
created_at timestamp(6) with time zone not null,
id bigint generated by default as identity,
user_id bigint not null,
provider varchar(50) not null,
provider_access_token varchar(2000),
provider_refresh_token varchar(2000),
provider_uid varchar(255) not null,
primary key (id),
constraint uk_identities_provider_uid unique (provider, provider_uid)
);
create table login_attempts (
success boolean not null,
attempted_at timestamp(6) with time zone not null,
id bigint generated by default as identity,
user_id bigint,
ip_address varchar(64) not null,
failure_reason varchar(100),
user_agent varchar(500),
primary key (id)
);
create table notification_hubs (
createdAt timestamp(6) with time zone not null,
id bigint generated by default as identity,
updatedAt timestamp(6) with time zone not null,
alertId varchar(255),
category varchar(255),
metadata TEXT,
notificationId varchar(255) not null unique,
templateId varchar(255) not null,
tenantId varchar(255),
userId varchar(255) not null,
status enum ('COMPLETED','CREATED','FAILED','PARTIAL_FAILURE','PROCESSING') not null,
primary key (id)
);
create table notification_preferences (
enabled boolean not null,
createdAt timestamp(6) with time zone not null,
id bigint generated by default as identity,
updatedAt timestamp(6) with time zone not null,
category varchar(255) not null,
tenantId varchar(255),
userId varchar(255) not null,
primary key (id),
unique (tenantId, userId, category)
);
create table notification_templates (
enabled boolean not null,
isMandatory boolean not null,
createdAt timestamp(6) with time zone,
id bigint generated by default as identity,
updatedAt timestamp(6) with time zone,
bodyTemplate TEXT not null,
category varchar(255),
createdBy varchar(255),
language varchar(255),
name varchar(255) not null,
subjectTemplate TEXT,
templateId varchar(255) not null unique,
templateType varchar(255) not null,
variablesDescription TEXT,
channel enum ('EMAIL','IN_APP','MOBILE_PUSH','SLACK','SMS','TEAMS','WEBSOCKET') not null,
primary key (id)
);
create table organizations (
created_at timestamp(6) with time zone not null,
id bigint generated by default as identity,
updated_at timestamp(6) with time zone not null,
slug varchar(100) not null unique,
name varchar(200) not null,
primary key (id)
);
create table permissions (
id bigint generated by default as identity,
permission_key varchar(100) not null unique,
description varchar(500),
primary key (id)
);
create table preference_channels (
preference_id bigint not null,
channel enum ('EMAIL','IN_APP','MOBILE_PUSH','SLACK','SMS','TEAMS','WEBSOCKET')
);
create table refresh_tokens (
created_at timestamp(6) with time zone not null,
expires_at timestamp(6) with time zone not null,
id bigint generated by default as identity,
revoked_at timestamp(6) with time zone,
rotated_from_id bigint,
session_id bigint not null,
token_hash varchar(255) not null unique,
primary key (id)
);
create table role_permissions (
permission_id bigint not null,
role_id bigint not null,
primary key (permission_id, role_id)
);
create table roles (
created_at timestamp(6) with time zone not null,
id bigint generated by default as identity,
org_id bigint,
name varchar(100) not null,
description varchar(500),
primary key (id)
);
create table sessions (
created_at timestamp(6) with time zone not null,
expires_at timestamp(6) with time zone not null,
id bigint generated by default as identity,
revoked_at timestamp(6) with time zone,
user_id bigint not null,
session_uuid varchar(36) not null unique,
token_hash varchar(255) not null unique,
primary key (id)
);
create table tracker_alerts (
acknowledged boolean,
resolved boolean,
acknowledged_at timestamp(6) with time zone,
alert_id bigint generated by default as identity,
created_at timestamp(6) with time zone,
organization_id bigint,
resolved_at timestamp(6) with time zone,
triggered_at timestamp(6) with time zone not null,
updated_at timestamp(6) with time zone,
acknowledged_by varchar(100),
resolved_by varchar(100),
locationId varchar(255),
message TEXT,
resolution_notes TEXT,
trackerId_id varchar(255),
vehicle_id varchar(255),
alert_type enum ('ACCIDENT_DETECTED','DEVICE_DISCONNECTED','ENGINE_ON_OUTSIDE_HOURS','FUEL_THEFT_SUSPECTED','GEOFENCE_DWELL_EXCEEDED','GEOFENCE_ENTRY','GEOFENCE_EXIT','GEOFENCE_VIOLATION','HARD_BRAKING','HIJACKING_SUSPECTED','IDLE_TIMEOUT','LONG_STOP','LOW_BATTERY','MAINTENANCE_DUE','NO_GPS_SIGNAL','OVERSPEED','PANIC_BUTTON_PRESSED','RAPID_ACCELERATION','ROUTE_DEVIATION','SCHEDULE_VIOLATION','TAMPER_DETECTED','UNAUTHORIZED_AREA','UNKNOWN') not null,
metadata JSONB,
severity enum ('CRITICAL','INFO','WARNING'),
primary key (alert_id)
);
create table tracker_assignments (
is_active boolean,
assigned_at timestamp(6) with time zone not null,
id bigint generated by default as identity,
removed_at timestamp(6) with time zone,
tracker_id varchar(50) not null,
vehicle_id varchar(50) not null,
assigned_by varchar(100),
removed_by varchar(100),
removal_reason varchar(200),
notes varchar(500),
primary key (id)
);
create table tracker_location_data (
acc_status boolean,
altitude float(24),
battery_voltage float(24),
heading float(24),
latitude float(53),
longitude float(53),
odometer_km float(24),
signal_strength integer,
speed_kmh float(24),
validity varchar(1),
created_at timestamp(6) with time zone,
location_id bigint generated by default as identity,
recorded_at timestamp(6) with time zone not null,
engine_status varchar(20),
tracker_id varchar(50) not null,
trip_id varchar(50),
device_status JSONB,
primary key (location_id)
);
create table tracker_raw_data (
processed boolean,
created_at timestamp(6) with time zone,
raw_data_id bigint generated by default as identity,
received_at timestamp(6) with time zone,
protocol varchar(20),
source_ip varchar(45),
tracker_id varchar(50) not null,
parsed_data JSONB,
processing_error TEXT,
raw_message TEXT not null,
primary key (raw_data_id)
);
create table trackers (
battery_level float(24),
is_online boolean,
signal_strength integer,
created_at timestamp(6) with time zone,
last_seen timestamp(6) with time zone,
updated_at timestamp(6) with time zone,
protocol varchar(20),
sim_number varchar(20),
device_id varchar(50) unique,
firmware_version varchar(50),
tracker_id varchar(50) not null,
vehicle_id varchar(50),
model varchar(100),
status enum ('ACTIVE','DECOMMISSIONED','INACTIVE','MAINTENANCE','STOLEN'),
primary key (tracker_id)
);
create table trip_points (
point_order integer not null,
segment_distance_km float(24),
segment_duration_minutes float(24),
created_at timestamp(6) with time zone,
location_id bigint not null unique,
trip_point_id bigint generated by default as identity,
trip_id varchar(50) not null,
primary key (trip_point_id)
);
create table trips (
acc_off_duration_seconds integer,
average_speed_kmh float(24),
fuel_consumed_liters float(24),
idle_time_minutes integer,
is_active boolean,
max_speed_kmh float(24),
total_distance_km float(24),
created_at timestamp(6) with time zone,
end_location_id bigint unique,
end_time timestamp(6) with time zone,
start_location_id bigint unique,
start_time timestamp(6) with time zone not null,
updated_at timestamp(6) with time zone,
trip_id varchar(50) not null,
vehicle_id varchar(50) not null,
end_reason enum ('ACC_OFF','CONNECTION_LOST','FUEL_CUT','GEOFENCE_EXIT','MANUAL','TIMEOUT'),
start_reason enum ('ACC_ON','AUTO_DETECTED','MANUAL','SCHEDULED'),
primary key (trip_id)
);
create table user_roles (
role_id bigint not null,
user_id bigint not null,
primary key (role_id, user_id)
);
create table users (
enabled boolean not null,
locked boolean not null,
created_at timestamp(6) with time zone not null,
id bigint generated by default as identity,
updated_at timestamp(6) with time zone not null,
first_name varchar(100),
last_name varchar(100),
email varchar(255) not null unique,
password_hash varchar(255),
primary key (id)
);
create table vehicles (
acc_status boolean,
fuel_level float(24),
is_fuel_cut_active boolean,
odometer_km float(24),
created_at timestamp(6) with time zone,
current_location_id bigint unique,
last_acc_off_time timestamp(6) with time zone,
last_acc_on_time timestamp(6) with time zone,
last_movement_time timestamp(6) with time zone,
last_telemetry_time timestamp(6) with time zone,
organization_id bigint,
updated_at timestamp(6) with time zone,
vin varchar(17),
license_plate varchar(20),
device_id varchar(50) unique,
vehicle_id varchar(50) not null,
model varchar(100),
engine_state enum ('AWAITING_CUTOFF','FUEL_CUT_ACTIVE','IDLE','MOVING','OFF','ON'),
primary key (vehicle_id)
);
create index idx_delivery_notification_id
on deliveries (notification_id);
create index idx_delivery_status_retry
on deliveries (status, nextRetryAt);
create index idx_delivery_channel
on deliveries (channel);
create index idx_delivery_created
on deliveries (createdAt desc);
create index idx_event_delivery_id
on delivery_events (deliveryId);
create index idx_event_occurred_at
on delivery_events (occurredAt desc);
create index idx_device_user_id
on devices (userId);
create index idx_device_push_token
on devices (pushToken);
create index idx_device_platform
on devices (platform);
create index idx_geofence_vehicles_vehicle_id
on geofence_vehicles (vehicle_id);
create index idx_hub_alert_id
on notification_hubs (alertId);
create index idx_hub_user_id
on notification_hubs (userId);
create index idx_hub_status
on notification_hubs (status);
create index idx_hub_created
on notification_hubs (createdAt desc);
create index idx_template_channel
on notification_templates (channel);
create index idx_template_type
on notification_templates (templateType);
create index idx_template_category
on notification_templates (category);
create index idx_template_enabled
on notification_templates (enabled);
alter table if exists alert_rule_vehicles
add constraint FKpstp2vhcbu318k2sejrl7aodx
foreign key (rule_id)
references alert_rules;
alter table if exists deliveries
add constraint FK23cs1w6rspfyacd6536g5ng2p
foreign key (notification_id)
references notification_hubs (notificationId);
alter table if exists device_commands
add constraint FKgdf1v6bu5gu6e7wh2myqlh4if
foreign key (tracker_id)
references trackers;
alter table if exists geofence_points
add constraint FKre0bykaowtfk9xyjccqodix1j
foreign key (geofence_id)
references geofences;
alter table if exists geofence_vehicles
add constraint FK7q6vj5bdwwk4q2wyg63r7afck
foreign key (geofence_id)
references geofences;
alter table if exists identities
add constraint FKlmyrd18386vbbpsgu8j79i7o7
foreign key (user_id)
references users;
alter table if exists login_attempts
add constraint FKtg9vhke4mlf5vij2rcvfk2dg2
foreign key (user_id)
references users;
alter table if exists preference_channels
add constraint FK6k5lhltqkjy9ivg59mppws9lv
foreign key (preference_id)
references notification_preferences;
alter table if exists refresh_tokens
add constraint FKcgeunry8ooahd3gtlqj2e5ysg
foreign key (rotated_from_id)
references refresh_tokens;
alter table if exists refresh_tokens
add constraint FKidma8aieax8yefj3f20u1ty7n
foreign key (session_id)
references sessions;
alter table if exists role_permissions
add constraint FKegdk29eiy7mdtefy5c7eirr6e
foreign key (permission_id)
references permissions;
alter table if exists role_permissions
add constraint FKn5fotdgk8d1xvo8nav9uv3muc
foreign key (role_id)
references roles;
alter table if exists roles
add constraint FKfaerb2evf6ya1atasp3e9d1e2
foreign key (org_id)
references organizations;
alter table if exists sessions
add constraint FKruie73rneumyyd1bgo6qw8vjt
foreign key (user_id)
references users;
alter table if exists tracker_assignments
add constraint FKtq2i2qjc7oaxe4bhka50ue7qr
foreign key (tracker_id)
references trackers;
alter table if exists tracker_assignments
add constraint FKjstfo0aod4cjlq9dhgxo3k198
foreign key (vehicle_id)
references vehicles;
alter table if exists tracker_location_data
add constraint FKqv6b5xlmfuya0p8vtlcuhsdrb
foreign key (tracker_id)
references trackers;
alter table if exists tracker_location_data
add constraint FKqv9kqjcncoisnjff4cxx1dqip
foreign key (trip_id)
references trips;
alter table if exists tracker_raw_data
add constraint FKogb5jywtat7jcslrgd50s6dm8
foreign key (tracker_id)
references trackers;
alter table if exists trackers
add constraint FKl4ss7rhgotmhv86tp230f2wox
foreign key (vehicle_id)
references vehicles;
alter table if exists trip_points
add constraint FKm9ycoeyoa04h49ost9aro2ova
foreign key (location_id)
references tracker_location_data;
alter table if exists trip_points
add constraint FK3yxhy53n7qd6l5635ebwqpeey
foreign key (trip_id)
references trips;
alter table if exists trips
add constraint FKpw7i2k754iurlmxe285lwmdwb
foreign key (end_location_id)
references tracker_location_data;
alter table if exists trips
add constraint FK4pt5fiyrkdoqgt0uw0p5p9e5g
foreign key (start_location_id)
references tracker_location_data;
alter table if exists trips
add constraint FKqahsaodjirbk4if91c9bfnlgg
foreign key (vehicle_id)
references vehicles;
alter table if exists user_roles
add constraint FKh8ciramu9cc9q3qcqiv4ue8a6
foreign key (role_id)
references roles;
alter table if exists user_roles
add constraint FKhfh9dx7w3ubf1co1vdev94g3f
foreign key (user_id)
references users;
alter table if exists vehicles
add constraint FK32eb4w6d6ust76629sjqof5x4
foreign key (current_location_id)
references tracker_location_data;